# Generated by Django 6.0.7 on 2026-08-02 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Drama, Comedy, Action)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title of the video', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the video content')),
                ('thumbnail', models.ImageField(blank=True, help_text='Preview image extracted from video for dashboard display', null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('original_video_file', models.FileField(help_text='Source video file (will be transcoded to 3 qualities by RQ worker)', upload_to='original_videos/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', help_text='Processing status for RQ worker tracking', max_length=20)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Video duration in seconds (populated after transcoding)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp for dashboard ordering (DESC)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag; inactive videos hidden from API')),
                ('categories', models.ManyToManyField(help_text='Genres this video belongs to', related_name='videos', to='videos_app.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('480p', '480p (SD)'), ('720p', '720p (HD)'), ('1080p', '1080p (Full HD)')], help_text='Target resolution for transcoded output (480p, 720p, 1080p)', max_length=10)),
                ('hls_manifest', models.FileField(help_text='HLS master playlist file (.m3u8) for this resolution', upload_to='hls/%Y/%m/%d/manifests/')),
                ('width', models.PositiveSmallIntegerField(help_text='Frame width in pixels')),
                ('height', models.PositiveSmallIntegerField(help_text='Frame height in pixels')),
                ('bitrate', models.PositiveIntegerField(help_text='Encoding bitrate in kbps')),
                ('processed_at', models.DateTimeField(auto_now_add=True, help_text='Transcoding completion timestamp')),
                ('video', models.ForeignKey(help_text='Parent video this resolution belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='videos_app.video')),
            ],
            options={
                'ordering': ['-height'],
            },
        ),
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(help_text="Segment filename (e.g., '000.ts', '001.ts')", max_length=50)),
                ('segment_file', models.FileField(help_text='Actual .ts video segment file', upload_to='hls/%Y/%m/%d/segments/')),
                ('sequence_index', models.PositiveIntegerField(help_text='Sequential order for HLS playback')),
                ('duration', models.DecimalField(decimal_places=3, help_text='Segment duration in seconds (typically 4-10 seconds)', max_digits=6)),
                ('resolution', models.ForeignKey(help_text='Resolution variant this segment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos_app.videoresolution')),
            ],
            options={
                'ordering': ['resolution', 'sequence_index'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status'], name='videos_app__status_b4cd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='videos_app__created_b2d6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_active', '-created_at'], name='videos_app__is_acti_d3f27e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoresolution',
            unique_together={('video', 'resolution')},
        ),
        migrations.AddIndex(
            model_name='videosegment',
            index=models.Index(fields=['resolution', 'sequence_index'], name='videos_app__resolut_0e7ca7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videosegment',
            unique_together={('resolution', 'segment_name')},
        ),
    ]
