# Generated by Django 6.0.7 on 2026-08-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosegment',
            name='segment_file',
        ),
        migrations.AddField(
            model_name='videosegment',
            name='segment_path',
            field=models.CharField(default='', help_text='Relative path to .ts video segment file', max_length=255),
        ),
        migrations.AlterField(
            model_name='videoresolution',
            name='hls_manifest',
            field=models.CharField(help_text='Relative path to HLS manifest file (.m3u8) for this resolution', max_length=255),
        ),
    ]
