"""Serializers for the user authentication app.

This module defines DRF serializers for registration, login,
password reset, and token refresh operations. Each serializer
validates incoming request data before passing it to the service layer.

Classes:
    RegisterSerializer: Validates registration data and creates users.
    LoginSerializer: Extends SimpleJWT TokenObtainPairSerializer with
        email-based authentication and user activity checks.
    PasswordResetRequestSerializer: Validates email for password reset.
    PasswordResetConfirmSerializer: Validates new password confirmation.
    TokenRefreshSerializer: Placeholder serializer for token refresh.
    UserSerializer: Read-only serializer for user representation.
"""

from rest_framework import serializers
from django.contrib.auth import get_user_model
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from user_auth_app.services import UserService

User = get_user_model()


class RegisterSerializer(serializers.Serializer):
    """Serializer for user registration requests.

    Validates that passwords match and that no duplicate email exists,
    then delegates user creation to the UserService.

    Attributes:
        email (EmailField): The user's email address.
        password (CharField): The chosen password (write-only).
        confirmed_password (CharField): Password confirmation (write-only).
    """

    email = serializers.EmailField(required=True)
    password = serializers.CharField(
        write_only=True, required=True, min_length=8)
    confirmed_password = serializers.CharField(write_only=True, required=True)

    def validate(self, attrs):
        """Validate that passwords match and email is unique.

        Args:
            attrs (dict): The deserialized input data.

        Returns:
            dict: The validated data.

        Raises:
            serializers.ValidationError: If passwords differ or email exists.
        """
        if attrs['password'] != attrs['confirmed_password']:
            raise serializers.ValidationError(
                {'confirmed_password': 'Passwords do not match.'}
            )

        email = attrs.get('email')
        if User.objects.filter(username=email).exists():
            raise serializers.ValidationError(
                {'email': 'A user with this email already exists.'}
            )

        return attrs

    def create(self, validated_data):
        """Create a new inactive user via UserService.

        Args:
            validated_data (dict): The validated registration data.

        Returns:
            User: The newly created inactive user instance.
        """
        password = validated_data.pop('password')
        user = UserService.create_inactive_user(
            validated_data['email'], password)
        return user


class LoginSerializer(TokenObtainPairSerializer):
    """Extends SimpleJWT TokenObtainPairSerializer for email authentication.

    Overrides the default username-based authentication to use email addresses.
    Also validates that the user account is active before issuing tokens.

    Tokens generated by this serializer are intended for HttpOnly cookies,
    not for client-side JavaScript consumption.

    Attributes:
        username_field (str): Set to 'username' which stores the email address.
    """

    username_field = User.USERNAME_FIELD

    @classmethod
    def get_token(cls, user):
        """Generate a JWT token pair for the authenticated user.

        Args:
            user (User): The authenticated user instance.

        Returns:
            Token: A SimpleJWT token object containing access and refresh tokens.
        """
        return super().get_token(user)

    def validate(self, attrs):
        """Validate credentials and ensure the account is active.

        Calls the parent validation method, then performs additional checks
        on the user's active status. Returns the token pair along with user
        information for the response body.

        Args:
            attrs (dict): The deserialized input data containing email and password.

        Returns:
            dict: A dictionary containing 'access', 'refresh' tokens and 'user' info.

        Raises:
            serializers.ValidationError: If the account is inactive.
        """
        data = super().validate(attrs)

        if not self.user.is_active:
            raise serializers.ValidationError({
                'detail': 'Please activate your account first.',
                'code': 'account_not_active'
            })

        data['user'] = {
            'id': self.user.id,
            'username': self.user.username,
            'email': self.user.username
        }

        return data


class PasswordResetRequestSerializer(serializers.Serializer):
    """Serializer for password reset request emails.

    Validates that a user with the given email exists before
    triggering the reset flow.

    Attributes:
        email (EmailField): The email address to send the reset link to.
    """

    email = serializers.EmailField(required=True)

    def validate_email(self, value):
        """Check that a user exists for the given email.

        Args:
            value (str): The email address to validate.

        Returns:
            str: The validated email address.

        Raises:
            serializers.ValidationError: If no user is found.
        """
        user = UserService.find_user_by_email(value)
        if not user:
            raise serializers.ValidationError('No user found with this email.')
        return value


class PasswordResetConfirmSerializer(serializers.Serializer):
    """Serializer for confirming a new password during reset.

    Validates that the new password and its confirmation match.

    Attributes:
        new_password (CharField): The new password (write-only).
        confirm_password (CharField): Password confirmation (write-only).
    """

    new_password = serializers.CharField(
        write_only=True, required=True, min_length=8)
    confirm_password = serializers.CharField(write_only=True, required=True)

    def validate(self, attrs):
        """Validate that the new passwords match.

        Args:
            attrs (dict): The deserialized input data.

        Returns:
            dict: The validated data.

        Raises:
            serializers.ValidationError: If the passwords do not match.
        """
        if attrs['new_password'] != attrs['confirm_password']:
            raise serializers.ValidationError(
                {'confirm_password': 'Passwords do not match.'}
            )
        return attrs


class TokenRefreshSerializer(serializers.Serializer):
    """Placeholder serializer for token refresh requests.

    The actual refresh token is read from the HTTP-only cookie,
    so no body fields are required.
    """
    pass


class UserSerializer(serializers.ModelSerializer):
    """Read-only serializer for user representation.

    Used in responses where user data is returned without
    exposing sensitive fields.

    Attributes:
        id (int): The user's primary key.
        username (str): The user's username (email address).
        email (str): The user's email address.
    """

    class Meta:
        model = User
        fields = ['id', 'username', 'email']
        read_only_fields = ['id', 'username', 'email']
